apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ai5n
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0052-tenant/tkrw-pr712-0075-0052-app/devfile-sample-ai5n@sha256:5e2f518c2d8069f7835ab9996d466fbea63ab7de34ead8e85df01b038765d704
        name: my-nodejs
        resources: {}
status: {}
